#pragma once


#define MASTER_RIGHT

#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM_PER_KEY

#define ENCODERS_PAD_A { B6 }
#define ENCODERS_PAD_B { B2 }
#define ENCODER_RESOLUTION 4

