#pragma once


#define MASTER_LEFT

#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM_PER_KEY

#define ENCODERS_PAD_A { B6, B4 }
#define ENCODERS_PAD_B { B2, B5 }
#define ENCODER_RESOLUTION 4
